apiVersion: apps/v1
kind: Deployment
metadata:
  name: moon
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: moon
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: moon
    spec:
      containers:
      - name: moon
        image: {{ .Values.moon.image }}
        args:
        - "-namespace"
        - "{{ .Release.Namespace }}"
        - "-license-file"
        - "/license/license.key"
{{- if .Values.resources.cpu.disabled }}
        - "-disable-cpu-limits"
{{ end -}}
{{- if .Values.resources.memory.disabled }}
        - "-disable-memory-limits"
{{ end -}}
{{- if .Values.moon.resources.enabled }}
        resources:
{{ toYaml .Values.moon.resources | indent 10 }}{{ end }}
        ports:
        - containerPort: {{ .Values.moon.port }}
        volumeMounts:
        - name: quota
          mountPath: /quota
          readOnly: true
        - name: users
          mountPath: /users
          readOnly: true
        - name: license-key
          mountPath: /license
          readOnly: true
      - name: moon-api
        image: {{ .Values.moonAPI.image }}
        args: ["-namespace", "{{ .Release.Namespace }}", "-license-file", "/license/license.key", "-listen", ":{{ .Values.moonAPI.port }}"]
{{- if .Values.moonAPI.resources.enabled }}
        resources:
{{ toYaml .Values.moonAPI.resources | indent 10 }}{{ end }}
        ports:
        - containerPort: {{ .Values.moonAPI.port }}
        volumeMounts:
        - name: quota
          mountPath: /quota
        - name: license-key
          mountPath: /license
          readOnly: true
      - name: moon-ui
        image: {{ .Values.moonUI.image }}
        args: ["-status-uri", "http://localhost:{{ .Values.moonAPI.port }}", "-webdriver-uri", "http://localhost:{{ .Values.moon.port }}"]
{{- if .Values.moonUI.resources.enabled }}
        resources:
{{ toYaml .Values.moonUI.resources | indent 10 }}{{ end }}
        ports:
        - name: moon-ui
          containerPort: {{ .Values.moonUI.port }}
      volumes:
      - name: quota
        configMap:
          name: quota
      - name: users
        secret:
          secretName: users
      - name: license-key
        secret:
          secretName: licensekey
