---
apiVersion: core/v1
kind: Service
metadata:
  name: moon
  namespace: {{ .Release.Namespace }}
spec:
{{- with .Values.service.externalIPs }}
  externalIPs:
  {{- range . }}
  - {{ . }}
  {{- end }}
{{- end }}
  selector:
    app: moon
  ports:
  - name: "moon"
    protocol: TCP
    port: {{ .Values.moon.port }}
  type: LoadBalancer

---
apiVersion: core/v1
kind: Service
metadata:
  name: moon-ui
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: moon
  ports:
  - name: "moon-ui"
    protocol: TCP
    port: {{ .Values.moonUI.port }}
  type: ClusterIP
